---
- name: Create ~/eclipse
  file:
    path: '{{ ansible_user_dir }}/eclipse/'
    state: directory

- name: Install eclipse
  unarchive:
    remote_src: yes
    src: 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2019-12/R/eclipse-committers-2019-12-R-linux-gtk-x86_64.tar.gz'
    # This will create ~/eclipse/eclipse, containing an eclipse executable.
    dest: '{{ ansible_user_dir }}/eclipse/'
    creates: '{{ ansible_user_dir }}/eclipse/eclipse/eclipse'
  tags:
    - eclipse

- name: Add eclipse.desktop file
  template:
    src: eclipse-local.desktop.j2
    dest: "{{ ansible_user_dir }}/.local/share/applications/eclipse-local.desktop"
  tags:
    - eclipse
