---
- name: tweak dnf a little bit
  lineinfile:
    path: "/etc/dnf/dnf.conf"
    line: "{{ item }}"
  with_items:
    - "fastestmirror=1"
    - "max_parallel_downloads=10"
    - "deltarpm=true"

- name: Install basic packages
  package:
    state: present
    name:
      - "@Fedora Workstation"
      - "@C Development Tools and Libraries"
#      - "@GNOME Desktop Environment"
      - "@3d-printing"
      - ImageMagick
      - alsa-utils
      - android-tools
      - ansible
      - ansible-collection-ansible-netcommon
      - ansible-collection-ansible-posix
      - ansible-collection-community-general
      - ansible-collection-community-kubernetes
      - ansible-collection-community-mysql
      - ansible-collection-containers-podman
      - ant
      - aspell
      - aspell-de
      - aspell-en
      - atop
      - autofs
      - automake
      - autossh
      - baobab
      - bind-utils
      - binutils
      - brasero
      - bridge-utils
      - byobu
      - cabextract
      - calibre
      - cifs-utils
      - coreutils
#      - chromium-browser-privacy
# Part of rpmfusion
      - dbus-tools
      - dconf-editor
      - desktop-backgrounds-basic
      - desktop-backgrounds-gnome
      - desktop-file-utils
      - distribution-gpg-keys
      - diffutils
      - dmidecode
      - dnf-utils
      - dnf-plugin-system-upgrade
      - docker
      - docker-compose
      - dos2unix
      - dosfstools
      - e2fsprogs
      - ecryptfs-utils
      - elfutils
      - eog
      - espeak
      - espeak-ng
      - etherape
      - evolution
      - evolution-ews
      - exiv2
      - fdupes
      - festival
      - file
      - findutils
      - firefox
      - flatpak
      - gconf-editor
      - gimp
      - gimp-help-de
      - git
      - git-extras
      - glabels
      - glabels-templates
      - gnome-tweaks
      - gnome-extensions-app
      - gparted
      - gradio
      - hdparm
      - hexchat
      - heimdall
      - highlight
      - hunspell-de
      - hyphen-de
      - imapfilter
      - indent
      - iputils
      - keepassxc
      - kernel-devel
      - langpacks-core-de
      - langpacks-de
      - lensfun
      - less
      - libreoffice
      - lm_sensors
      - lshw
      - lsof
      - make
      - mkpasswd
      - mosquitto
#      - mplayer
      - mtools
      - mythes-de
      - net-tools
      - nethogs
      - netpbm
      - nextcloud-client
      - nextcloud-client-nautilus
      - nfs-utils
      - nmap
      - ntfsprogs
      - openssh
      - openssl
      - openvpn
      - os-prober
      - p0f
      - patch
      - patchutils
      - perl-Image-ExifTool
      - php-cli
      - pidgin
      - pidgin-indicator
      - poedit
      - poppler-utils
      - powerline
      - powerline-fonts
      - powertop
      - psmisc
      - pulseaudio-utils
      - python3-libselinux
      - python3-ansible-lint
      - python3-netaddr
      - python3-dnf-plugin-versionlock
      - qelectrotech
      - rdesktop
      - recode
      - remmina
      - remmina-plugins-exec
      - remmina-plugins-rdp
      - remmina-plugins-secret
      - remmina-plugins-st
      - remmina-plugins-vnc
      - rhythmbox
      - rsync
      - screen
      - seahorse
      - setroubleshoot
      - setroubleshoot-plugins
      - sloccount
      - smartmontools
      - sox
      - sqlite
      - strace
      - subversion
      - swaks
      - symlinks
      - tar
      - tcpdump
      - telnet
      - testdisk
      - texlive
#      - thunderbird
#      - thunderbird-enigmail
# wayland got default, enigmail no longer avail
      - thunderbird-wayland
      - tmux
      - tmux-powerline
      - traceroute
      - tree
      - ufraw
#      - ungoogled-chromium
      - usbutils
      - vim-X11
      - vim-enhanced
      - vim-powerline
      - vinagre
#      - vino
# not yet in 34
      - virt-manager
#      - vlc
#      - vlc-extras
      - wget
      - which
      - wireshark
      - wmctrl
      - xdg-utils
      - xdotool
      - xmlrpc-client
      - yamllint
      - zip

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks from flathub
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  with_items:
    - org.signal.Signal
#    - de.haeckerfelix.Shortwave
# Up to now not used by myself and just cluttering selinux problems.

- name: vscodium - import required gpgkey
  rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg

- name: vscodium - add required repository
  yum_repository:
    name: gitlab.com_paulcarroty_vscodium_repo
    description: Binary release repo for VSCodium
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    gpgcheck: yes
    repo_gpgcheck: yes

- name: vscodium - install binary
  package:
    state: present
    name:
      - codium

- name: enable sshd.service
  systemd:
    name: sshd
    enabled: yes
    state: started

- name: install rpm fusion - free
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: install rpm fusion - free tainted
  dnf:
    name: "rpmfusion-free-release-tainted"
    state: present
  when: ansible_distribution == 'Fedora'

- name: install rpm fusion - nonfree
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: update dnf
  dnf:
    name: 
      - dnf-plugins-core
      - vlc
      - libdvdcss
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-extras
#      - gstreamer1-plugins-freeworld
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-good-gtk
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-ugly-free
      - gstreamer1-plugin-openh264 
      - mozilla-openh264
    state: present

- name: create power optimization
  copy:
    dest: "/etc/power_setup"
    owner: "root"
    mode: "u+rwx,go=r"
    content: |
      #!/bin/bash
      echo '1500' > /proc/sys/vm/dirty_writeback_centisecs
      echo '0' > /proc/sys/kernel/nmi_watchdog
      echo 'auto' > /sys/bus/i2c/devices/i2c-12/device/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:00:12.0/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:00:04.0/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:00:1f.0/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:73:00.0/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:01:00.0/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:00:1f.5/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:00:00.0/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:00:14.2/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:72:00.0/power/control
      echo 'auto' > /sys/bus/pci/devices/0000:00:14.2/power/control

- name: create systemd file for power_setup
  copy:
    dest: "/lib/systemd/system/power_setup_startup.service"
    owner: "root"
    mode: "u+rw,go=r"
    content: |
      [Unit]
      Description=A service to setup power saving features
      After=network.target

      [Service]
      Type=simple
      User=root
      ExecStart=/etc/power_setup

      [Install]
      WantedBy=multi-user.target

- name: enable systemd startup power_setup
  systemd:
    name: "power_setup_startup"
    enabled: yes
    state: started

- name: pip install ansible
  ansible.builtin.pip:
    name: {{ item }}
  with_itmes:
    - "ansible==2.10.7"
    - "ansible-base==2.10.7"
    - "ansible-lint"
