---
- name: Install basic packages
  package:
    state: present
    name:
      - "@Fedora Workstation"
      - "@C Development Tools and Libraries"
      - "@GNOME Desktop Environment"
      - ImageMagick
      - alacarte
      - alsa-utils
      - android-tools
      - ansible
      - ant
      - aspell
      - aspell-de
      - aspell-en
      - atop
      - automake
      - baobab
      - bind-utils
      - binutils
      - brasero
      - bridge-utils
      - byobu
      - cabextract
      - calibre
      - cifs-utils
      - coreutils
      - dbus-tools
      - dconf-editor
      - desktop-backgrounds-basic
      - desktop-backgrounds-gnome
      - desktop-file-utils
      - diffutils
      - dmidecode
      - dnf-utils
      - docker
      - docker-compose
      - dos2unix
      - dosfstools
      - e2fsprogs
      - elfutils
      - eog
      - espeak
      - espeak-ng
      - etherape
      - evolution
      - evolution-ews
      - exiv2
      - fdupes
      - festival
      - file
      - findutils
      - firefox
      - flatpak
      - gconf-editor
      - gimp
      - gimp-help-de
      - git
      - git-extras
      - glabels
      - glabels-templates
      - gparted
      - gradio
      - gstreamer-tools
      - hdparm
      - heimdall
      - highlight
      - hunspell-de
      - hyphen-de
      - imapfilter
      - indent
      - iputils
      - keepassxc
      - langpacks-core-de
      - langpacks-de
      - lensfun
      - less
      - libreoffice
      - lm_sensors
      - lshw
      - lsof
      - make
      - mkpasswd
      - mplayer
      - mtools
      - mythes-de
      - net-tools
      - nethogs
      - netpbm
      - nextcloud-client
      - nextcloud-client-nautilus
      - nfs-utils
      - nmap
      - ntfsprogs
      - openssh
      - openvpn
      - os-prober
      - p0f
      - patch
      - patchutils
      - perl-Image-ExifTool
      - php-cli
      - pidgin
      - pidgin-indicator
      - poedit
      - poppler-utils
      - powerline
      - powerline-fonts
      - psmisc
      - pulseaudio-utils
      - python3-libselinux
      - python3-ansible-lint
      - rdesktop
      - recode
      - remmina
      - remmina-plugins-exec
      - remmina-plugins-rdp
      - remmina-plugins-secret
      - remmina-plugins-st
      - remmina-plugins-vnc
      - rhythmbox
      - rsync
      - screen
      - seahorse
      - setroubleshoot
      - setroubleshoot-plugins
      - sloccount
      - smartmontools
      - sox
      - sqlite
      - strace
      - subversion
      - swaks
      - symlinks
      - tar
      - tcpdump
      - telnet
      - testdisk
      - texlive
      - thunderbird
      - thunderbird-enigmail
      - thunderbird-wayland
      - tmux
      - tmux-powerline
      - traceroute
      - tree
      - ufraw
      - usbutils
      - vim-X11
      - vim-enhanced
      - vim-powerline
      - vinagre
      - vino
      - vlc
      - vlc-extras
      - wget
      - which
      - wireshark
      - wmctrl
      - xdg-utils
      - xdotool
      - xmlrpc-client
      - yamllint
      - zip
